---
title: "The B0ardside"
contentDir: "content"
layoutDir: "layouts"
publishDir: "public"
buildDrafts: false
taxonomies:
   category: "categories"
   tag: "tags"
baseURL: "http://theb0ardside.com"
params:
    SidebarRecentLimit: 5
markup:
  goldmark:
    renderer:
      unsafe: true
...
